url: "https://centralcoastpharmacyservices.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Central Coast Pharmacy Services" # the name of your site, e.g. ACME Corp.
description: "At Central Coast Pharmacy Services, we understand it takes compassion to provide you with quality services that you deserve in fulfilling your medication needs. Medication delivery for Monterey, Carmel, Salinas, Big Sur and surrounding areas!"
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "" 
      type: "pages"
    values:
      layout: "default"